import express from 'express';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import multer from 'multer';
import bcrypt from 'bcryptjs';
import readXlsxFile from 'read-excel-file/node';
import { parseEmployeeRows } from './employee-schedule-parser.js';
import { createWorker } from 'tesseract.js';
import path from 'node:path';
import fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { pool, id, migrate, tx, createDatabaseBackup, closeDatabase } from './db.js';
import { allow, authenticate, createAccount, ensureAdmin, login, logout, publicAccount } from './auth.js';
import { parseFlightText } from './flight-parser.js';
import { autoSchedule } from './scheduler.js';
import { parseScheduleTsv } from './image-schedule-parser.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const upload = multer({ dest: path.join(root, 'data/uploads'), limits: { fileSize: 15 * 1024 * 1024 } });
const app = express();
app.disable('x-powered-by');
app.use(helmet({ contentSecurityPolicy: { directives: { defaultSrc: ["'self'"], scriptSrc: ["'self'", "'unsafe-inline'"], styleSrc: ["'self'", "'unsafe-inline'"] } } }));
app.use(express.json({ limit: '1mb' })); app.use(cookieParser());
app.post('/api/auth/login', login); app.post('/api/auth/logout', logout);
app.use('/api', authenticate);

app.get('/api/me', (req,res) => res.json({ account: req.account }));
app.get('/api/dashboard', async (req,res,next) => { try {
  const date = req.query.date || new Date().toISOString().slice(0,10);
  const [flights, employees, coverage] = await Promise.all([
    pool.query(`SELECT f.*,(f.international OR COALESCE(al.international,false)) is_international,COALESCE(al.lead_required,1) lead_required,COALESCE(al.agent_required,2) agent_required,
      COALESCE(json_agg(json_build_object('id',a.id,'employeeId',e.id,'name',e.name,'role',a.role,'locked',a.locked)) FILTER(WHERE a.id IS NOT NULL),'[]') assignments
      FROM flights f LEFT JOIN airlines al ON al.code=f.airline LEFT JOIN assignments a ON a.flight_id=f.id LEFT JOIN employees e ON e.id=a.employee_id
      WHERE f.service_date=$1 GROUP BY f.id,al.lead_required,al.agent_required,al.international ORDER BY COALESCE(f.arrival_at,f.departure_at)`, [date]),
    pool.query(`SELECT e.*,s.starts_at,s.ends_at,(c.id IS NOT NULL) called_out FROM employees e LEFT JOIN shifts s ON s.employee_id=e.id AND s.work_date=$1 LEFT JOIN callouts c ON c.employee_id=e.id AND c.work_date=$1 WHERE e.deleted_at IS NULL ORDER BY e.name`, [date]),
    pool.query(`SELECT slots.slot, count(s.id) FILTER(WHERE s.starts_at<=slots.slot AND s.ends_at>slots.slot AND c.id IS NULL) employees
      FROM generate_series($1::date,$1::date+interval '1 day',interval '30 min') slots(slot)
      LEFT JOIN shifts s ON s.work_date=$1 LEFT JOIN callouts c ON c.employee_id=s.employee_id AND c.work_date=$1 GROUP BY slots.slot ORDER BY slots.slot`, [date])
  ]);
  res.json({ date, flights: flights.rows, employees: employees.rows, coverage: coverage.rows });
} catch(e){next(e)} });

app.post('/api/flights/parse', allow('admin','scheduler'), (req,res) => res.json({ flights: parseFlightText(String(req.body.text || ''), req.body.date || new Date().toISOString().slice(0,10)) }));
app.post('/api/flights/import', allow('admin','scheduler'), async (req,res,next) => { try {
  const rows = Array.isArray(req.body.flights) ? req.body.flights : [];
  await tx(async c => { for (const f of rows) await c.query(`INSERT INTO flights(id,service_date,airline,arrival_number,departure_number,origin,destination,arrival_at,departure_at,gate,aircraft,notes,ferry,priority,international) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`, [id(),req.body.date,f.airline,f.arrivalNumber,f.departureNumber,f.origin,f.destination,f.arrivalAt,f.departureAt,f.gate,f.aircraft,f.notes,!!f.ferry,!!f.priority,!!f.international]); });
  res.status(201).json({ imported: rows.length });
} catch(e){next(e)} });
app.post('/api/flights', allow('admin','scheduler'), async (req,res,next) => { try { const f=req.body; const result=await pool.query(`INSERT INTO flights(id,service_date,airline,arrival_number,departure_number,origin,destination,arrival_at,departure_at,gate,notes,priority,ferry,international) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[id(),f.serviceDate,f.airline.toUpperCase(),f.arrivalNumber||null,f.departureNumber||null,f.origin||null,f.destination||null,f.arrivalAt||null,f.departureAt||null,f.gate||null,f.notes||null,!!f.priority,!!f.ferry,!!f.international]);res.status(201).json(result.rows[0]); }catch(e){next(e)} });
app.patch('/api/flights/:id', allow('admin','scheduler'), async(req,res,next)=>{try{const f=req.body;const r=await pool.query(`UPDATE flights SET airline=COALESCE($2,airline),arrival_number=$3,departure_number=$4,origin=$5,destination=$6,arrival_at=$7,departure_at=$8,gate=$9,notes=$10,priority=$11,ferry=$12,international=$13 WHERE id=$1 RETURNING *`,[req.params.id,f.airline?.toUpperCase()||null,f.arrivalNumber||null,f.departureNumber||null,f.origin?.toUpperCase()||null,f.destination?.toUpperCase()||null,f.arrivalAt||null,f.departureAt||null,f.gate||null,f.notes||null,!!f.priority,!!f.ferry,!!f.international]);if(!r.rows.length)return res.status(404).json({error:'Flight not found'});res.json(r.rows[0])}catch(e){next(e)}});
app.delete('/api/flights/:id', allow('admin','scheduler'), async(req,res,next)=>{try{await pool.query('DELETE FROM flights WHERE id=$1',[req.params.id]);res.status(204).end()}catch(e){next(e)}});
app.delete('/api/flights', allow('admin','scheduler'), async(req,res,next)=>{try{if(!req.query.date)return res.status(400).json({error:'Operating date is required'});await pool.query('DELETE FROM flights WHERE service_date=$1',[req.query.date]);res.status(204).end()}catch(e){next(e)}});
app.post('/api/schedule/run', allow('admin','scheduler'), async(req,res,next)=>{try{res.json(await autoSchedule(req.body.date))}catch(e){next(e)}});
app.post('/api/assignments', allow('admin','scheduler'), async(req,res,next)=>{try{const a=req.body;if(['lead','supervisor'].includes(a.role)){const allowed=await pool.query(`SELECT e.primary_role,f.airline,q.can_lead FROM employees e JOIN flights f ON f.id=$2 LEFT JOIN employee_qualifications q ON q.employee_id=e.id AND q.airline=f.airline WHERE e.id=$1`,[a.employeeId,a.flightId]);const candidate=allowed.rows[0];if(!candidate)return res.status(404).json({error:'Employee or flight not found'});if(!['lead','supervisor'].includes(candidate.primary_role))return res.status(400).json({error:'Only leads and supervisors can run a flight'});if(!candidate.can_lead)return res.status(400).json({error:`This employee is not authorized to run ${candidate.airline} flights`});}const assignmentRole=a.role==='supervisor'?'lead':a.role;const r=await pool.query(`INSERT INTO assignments(id,flight_id,employee_id,role,locked) VALUES($1,$2,$3,$4,true) ON CONFLICT(flight_id,employee_id) DO UPDATE SET role=EXCLUDED.role,locked=true RETURNING *`,[id(),a.flightId,a.employeeId,assignmentRole]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
app.delete('/api/assignments/:id', allow('admin','scheduler'), async(req,res,next)=>{try{await pool.query('DELETE FROM assignments WHERE id=$1',[req.params.id]);res.status(204).end()}catch(e){next(e)}});

app.get('/api/employees', async(req,res,next)=>{try{res.json({employees:(await pool.query(`SELECT e.*,COALESCE(json_agg(q.*) FILTER(WHERE q.employee_id IS NOT NULL),'[]') qualifications FROM employees e LEFT JOIN employee_qualifications q ON q.employee_id=e.id WHERE e.deleted_at IS NULL GROUP BY e.id ORDER BY e.pending_deletion,CASE e.primary_role WHEN 'supervisor' THEN 1 WHEN 'lead' THEN 2 WHEN 'agent' THEN 3 ELSE 4 END,e.name`)).rows})}catch(e){next(e)}});
app.get('/api/employees/trash', allow('admin'), async(req,res,next)=>{try{res.json({employees:(await pool.query('SELECT id,name,primary_role,deleted_at FROM employees WHERE deleted_at IS NOT NULL ORDER BY deleted_at DESC')).rows})}catch(e){next(e)}});
app.delete('/api/employees/trash', allow('admin'), async(req,res,next)=>{try{const r=await pool.query('DELETE FROM employees WHERE deleted_at IS NOT NULL');res.json({deleted:r.affectedRows??r.rowCount??0})}catch(e){next(e)}});
app.get('/api/airlines', async(req,res,next)=>{try{res.json({airlines:(await pool.query('SELECT * FROM airlines ORDER BY code')).rows})}catch(e){next(e)}});
app.post('/api/employees', allow('admin'), async(req,res,next)=>{try{const e=req.body;const r=await pool.query(`INSERT INTO employees(id,name,normalized_name,primary_role,eligible_roles) VALUES($1,$2,$3,$4,$5) RETURNING *`,[id(),e.name,e.name.trim().toLowerCase(),e.primaryRole||'agent',e.eligibleRoles||['agent']]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
app.patch('/api/employees/:id', allow('admin'), async(req,res,next)=>{try{const e=req.body;const r=await pool.query(`UPDATE employees SET name=COALESCE($2,name),primary_role=COALESCE($3,primary_role),eligible_roles=COALESCE($4,eligible_roles),pending_deletion=COALESCE($5,pending_deletion),tow_qualified=COALESCE($6,tow_qualified),customs_seal=COALESCE($7,customs_seal),updated_at=now() WHERE id=$1 RETURNING *`,[req.params.id,e.name||null,e.primaryRole||null,e.eligibleRoles||null,e.pendingDeletion,e.towQualified,e.customsSeal]);res.json(r.rows[0])}catch(e){next(e)}});
app.put('/api/employees/:id/qualifications/:airline', allow('admin'), async(req,res,next)=>{try{const q=req.body;const airline=req.params.airline.toUpperCase();const exists=await pool.query('SELECT 1 FROM airlines WHERE code=$1',[airline]);if(!exists.rows.length)return res.status(400).json({error:'Select an airline created in Administration'});const r=await tx(async c=>{const saved=await c.query(`INSERT INTO employee_qualifications(employee_id,airline,priority,can_lead,can_tow) VALUES($1,$2,$3,$4,$5) ON CONFLICT(employee_id,airline) DO UPDATE SET priority=EXCLUDED.priority,can_lead=EXCLUDED.can_lead,can_tow=EXCLUDED.can_tow RETURNING *`,[req.params.id,airline,Number(q.priority||50),!!q.canLead,!!q.towQualified]);await c.query('UPDATE employees SET tow_qualified=$2,customs_seal=$3,updated_at=now() WHERE id=$1',[req.params.id,!!q.towQualified,!!q.customsSeal]);return saved.rows[0]});res.json(r)}catch(e){next(e)}});
app.delete('/api/employees/:id', allow('admin'), async(req,res,next)=>{try{if(req.query.permanent==='true') await pool.query('DELETE FROM employees WHERE id=$1',[req.params.id]);else await pool.query('UPDATE employees SET deleted_at=now() WHERE id=$1',[req.params.id]);res.status(204).end()}catch(e){next(e)}});
app.post('/api/employees/:id/restore', allow('admin'), async(req,res,next)=>{try{const r=await pool.query('UPDATE employees SET deleted_at=NULL,pending_deletion=false,updated_at=now() WHERE id=$1 AND deleted_at IS NOT NULL RETURNING *',[req.params.id]);if(!r.rows.length)return res.status(404).json({error:'Trashed employee not found'});res.json(r.rows[0])}catch(e){next(e)}});
app.delete('/api/employees', allow('admin'), async(req,res,next)=>{try{await pool.query('UPDATE employees SET deleted_at=now() WHERE deleted_at IS NULL');res.status(204).end()}catch(e){next(e)}});
app.delete('/api/shifts', allow('admin','scheduler'), async(req,res,next)=>{try{if(!req.query.from||!req.query.to)return res.status(400).json({error:'Schedule date range is required'});await pool.query('DELETE FROM shifts WHERE work_date BETWEEN $1 AND $2',[req.query.from,req.query.to]);res.status(204).end()}catch(e){next(e)}});
app.get('/api/employees/:id/shifts', async(req,res,next)=>{try{const from=req.query.from||new Date().toISOString().slice(0,10),to=req.query.to||from;const r=await pool.query('SELECT * FROM shifts WHERE employee_id=$1 AND work_date BETWEEN $2 AND $3 ORDER BY work_date',[req.params.id,from,to]);res.json({shifts:r.rows})}catch(e){next(e)}});
app.put('/api/employees/:id/shifts/:date', allow('admin','scheduler'), async(req,res,next)=>{try{const {start,end}=req.body;if(!/^\d{2}:\d{2}$/.test(start||'')||!/^\d{2}:\d{2}$/.test(end||''))return res.status(400).json({error:'Enter a start and end time'});const workDate=req.params.date;const next=new Date(`${workDate}T12:00:00`);if(end<=start)next.setDate(next.getDate()+1);const endDate=next.toISOString().slice(0,10);const r=await pool.query(`INSERT INTO shifts(id,employee_id,work_date,starts_at,ends_at,source) VALUES($1,$2,$3,$4,$5,'manual') ON CONFLICT(employee_id,work_date) DO UPDATE SET starts_at=EXCLUDED.starts_at,ends_at=EXCLUDED.ends_at,source='manual',import_id=NULL RETURNING *`,[id(),req.params.id,workDate,`${workDate}T${start}:00`,`${endDate}T${end}:00`]);res.json(r.rows[0])}catch(e){next(e)}});
app.delete('/api/employees/:id/shifts/:date', allow('admin','scheduler'), async(req,res,next)=>{try{await pool.query('DELETE FROM shifts WHERE employee_id=$1 AND work_date=$2',[req.params.id,req.params.date]);res.status(204).end()}catch(e){next(e)}});
app.post('/api/callouts', allow('admin','scheduler'), async(req,res,next)=>{try{const c=req.body;await pool.query(`INSERT INTO callouts(id,employee_id,work_date,reason) VALUES($1,$2,$3,$4) ON CONFLICT(employee_id,work_date) DO UPDATE SET reason=EXCLUDED.reason`,[id(),c.employeeId,c.date,c.reason||null]);res.status(201).json({ok:true})}catch(e){next(e)}});
app.delete('/api/callouts/:employeeId/:date', allow('admin','scheduler'), async(req,res,next)=>{try{await pool.query('DELETE FROM callouts WHERE employee_id=$1 AND work_date=$2',[req.params.employeeId,req.params.date]);res.status(204).end()}catch(e){next(e)}});

app.post('/api/employees/import', allow('admin'), upload.single('file'), async(req,res,next)=>{try{
  let rows=[],parsed; const ext=path.extname(req.file.originalname).toLowerCase();
  if(ext==='.xlsx') rows=await readXlsxFile(req.file.path);
  else if(ext==='.csv') rows=parseCsv(await fs.readFile(req.file.path,'utf8'));
  else {const worker=await createWorker('eng');const out=await worker.recognize(req.file.path,{}, {tsv:true});await worker.terminate();parsed=parseScheduleTsv(out.data.tsv,req.body.weekStart);}
  await fs.unlink(req.file.path).catch(()=>{}); parsed??=parseEmployeeRows(rows,req.body.weekStart); res.json({preview:parsed});
}catch(e){next(e)}});
app.post('/api/employees/import/commit', allow('admin'), async(req,res,next)=>{try{const incoming=req.body.employees||[];const importId=id();await tx(async c=>{
  await c.query('UPDATE employees SET pending_deletion=true WHERE deleted_at IS NULL');
  for(const e of incoming){const normalized=e.name.trim().toLowerCase();const er=await c.query(`INSERT INTO employees(id,name,normalized_name,primary_role,eligible_roles,pending_deletion,customs_seal) VALUES($1,$2,$3,$4,$5,false,$6) ON CONFLICT(normalized_name) DO UPDATE SET name=EXCLUDED.name,primary_role=EXCLUDED.primary_role,eligible_roles=EXCLUDED.eligible_roles,pending_deletion=false,customs_seal=EXCLUDED.customs_seal,updated_at=now() RETURNING id`,[id(),e.name,normalized,e.role||'agent',[e.role||'agent'],!!e.customsSeal]);for(const s of e.shifts||[]) await c.query(`INSERT INTO shifts(id,employee_id,work_date,starts_at,ends_at,source,import_id) VALUES($1,$2,$3,$4,$5,'import',$6) ON CONFLICT(employee_id,work_date) DO UPDATE SET starts_at=EXCLUDED.starts_at,ends_at=EXCLUDED.ends_at,source='import',import_id=EXCLUDED.import_id`,[id(),er.rows[0].id,s.date,s.start,s.end,importId]);}
  await c.query(`INSERT INTO imports(id,kind,status,summary) VALUES($1,'employees','complete',$2)`,[importId,JSON.stringify({employees:incoming.length})]);});res.status(201).json({imported:incoming.length})}catch(e){next(e)}});

app.get('/api/admin', allow('admin'), async(req,res,next)=>{try{const [accounts,airlines,issues,settings]=await Promise.all([pool.query('SELECT id,username,role,active,employee_id FROM accounts ORDER BY username'),pool.query('SELECT * FROM airlines ORDER BY code'),pool.query('SELECT * FROM issues ORDER BY created_at DESC'),pool.query('SELECT * FROM settings')]);res.json({accounts:accounts.rows.map(publicAccount),airlines:airlines.rows,issues:issues.rows,settings:Object.fromEntries(settings.rows.map(x=>[x.key,x.value]))})}catch(e){next(e)}});
app.post('/api/admin/accounts', allow('admin'), async(req,res,next)=>{try{res.status(201).json(await createAccount(req.body))}catch(e){next(e)}});
app.patch('/api/admin/accounts/:id', allow('admin'), async(req,res,next)=>{try{const a=req.body,current=await pool.query('SELECT * FROM accounts WHERE id=$1',[req.params.id]);if(!current.rows.length)return res.status(404).json({error:'Account not found'});if(req.params.id===req.account.id&&a.active===false)return res.status(400).json({error:'You cannot deactivate your own account'});if(current.rows[0].role==='admin'&&((a.role&&a.role!=='admin')||a.active===false)){const admins=await pool.query("SELECT count(*)::int count FROM accounts WHERE role='admin' AND active=true");if(Number(admins.rows[0].count)<=1)return res.status(400).json({error:'At least one active administrator is required'})}if(a.password!==undefined&&String(a.password).length<12)return res.status(400).json({error:'New password must be at least 12 characters'});const hash=a.password?await bcrypt.hash(String(a.password),12):null;const r=await pool.query(`UPDATE accounts SET username=COALESCE($2,username),role=COALESCE($3,role),active=COALESCE($4,active),password_hash=COALESCE($5,password_hash) WHERE id=$1 RETURNING id,username,role,active,employee_id`,[req.params.id,a.username?.trim().toLowerCase()||null,a.role||null,a.active,hash]);if(hash)await pool.query('DELETE FROM sessions WHERE account_id=$1',[req.params.id]);res.json(publicAccount(r.rows[0]))}catch(e){next(e)}});
app.delete('/api/admin/accounts/:id', allow('admin'), async(req,res,next)=>{try{if(req.params.id===req.account.id)return res.status(400).json({error:'You cannot delete your own account'});const current=await pool.query('SELECT role,active FROM accounts WHERE id=$1',[req.params.id]);if(!current.rows.length)return res.status(404).json({error:'Account not found'});if(current.rows[0].role==='admin'&&current.rows[0].active){const admins=await pool.query("SELECT count(*)::int count FROM accounts WHERE role='admin' AND active=true");if(Number(admins.rows[0].count)<=1)return res.status(400).json({error:'At least one active administrator is required'})}await pool.query('DELETE FROM accounts WHERE id=$1',[req.params.id]);res.status(204).end()}catch(e){next(e)}});
app.post('/api/admin/airlines', allow('admin'), async(req,res,next)=>{try{const a=req.body;const r=await pool.query(`INSERT INTO airlines(code,name,lead_required,agent_required,arrival_lead_minutes,post_departure_minutes,international) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(code) DO UPDATE SET name=EXCLUDED.name,lead_required=EXCLUDED.lead_required,agent_required=EXCLUDED.agent_required,arrival_lead_minutes=EXCLUDED.arrival_lead_minutes,post_departure_minutes=EXCLUDED.post_departure_minutes,international=EXCLUDED.international RETURNING *`,[a.code.toUpperCase(),a.name,Number(a.leadRequired),Number(a.agentRequired),Number(a.arrivalLeadMinutes||15),Number(a.postDepartureMinutes||10),!!a.international]);res.json(r.rows[0])}catch(e){next(e)}});
app.post('/api/issues', async(req,res,next)=>{try{const i=req.body,detail=String(i.detail||'').trim();if(!detail)return res.status(400).json({error:'Issue details are required'});const title=String(i.title||'').trim()||'Issue report';const r=await pool.query('INSERT INTO issues(id,title,detail,reported_by) VALUES($1,$2,$3,$4) RETURNING *',[id(),title,detail,req.account.id]);if(process.env.DISCORD_WEBHOOK_URL) fetch(process.env.DISCORD_WEBHOOK_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({content:`FlightDeck issue\n${detail}`})}).catch(()=>{});res.status(201).json(r.rows[0])}catch(e){next(e)}});
app.post('/api/admin/backup', allow('admin'), async(req,res,next)=>{try{const filename=await createDatabaseBackup('manual');res.status(201).json({message:`Backup created: ${filename}`})}catch(e){next(e)}});

app.use(express.static(path.join(root,'public'))); app.get('/{*splat}',(_,res)=>res.sendFile(path.join(root,'public','index.html')));
app.use((err,req,res,_next)=>{console.error(err);res.status(err.code==='LIMIT_FILE_SIZE'?413:400).json({error:process.env.NODE_ENV==='production'?'The request could not be completed':err.message})});

function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x!==''))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(x=>x!==''))rows.push(row);return rows}

await fs.mkdir(path.join(root,'data/uploads'),{recursive:true}); await migrate(); await ensureAdmin();
const pruneAssignments=()=>pool.query(`DELETE FROM assignments a USING flights f WHERE a.flight_id=f.id AND f.service_date < current_date-1`).catch(console.error);
await pruneAssignments(); setInterval(pruneAssignments,6*60*60*1000).unref();
function scheduleNightlyBackup(){const now=new Date(),next=new Date(now);next.setHours(2,0,0,0);if(next<=now)next.setDate(next.getDate()+1);setTimeout(async()=>{try{await createDatabaseBackup('nightly')}catch(error){console.error('Nightly backup failed',error)}scheduleNightlyBackup()},next-now).unref()}
scheduleNightlyBackup();
const port=Number(process.env.PORT||3000),host=process.env.HOST||'0.0.0.0';const server=app.listen(port,host,()=>console.log(`FlightDeck listening on http://${host}:${port}`));
let shuttingDown=false;async function shutdown(){if(shuttingDown)return;shuttingDown=true;server.close();try{await closeDatabase()}finally{process.exit(0)}}
process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
