name: Deploy to Rubberducky

on:
  push:
    branches:
      - main
permissions: {}

concurrency:
  group: flightschedule-deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy FlightSchedule
    runs-on:
      - self-hosted
      - linux

    steps:
      - name: Update FlightSchedule
        run: |
          set -e

          echo "=== Updating repository ==="
          cd /root/flightschedule

          git pull

          echo "=== Updating Docker ==="
          docker restart flightschedule-app-1

          echo "=== Container status ==="
          docker ps

          echo "=== Deployment complete ==="
